[project]
name = "mcp-codebeamer-cbql"
version = "0.1.0"
description = "Codebeamer MCP server focusing on CBQL"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.3",
    "httpx>=0.28.1",
]
